/*
 * Copyright 2013 Sander Verdonschot <sander.verdonschot at gmail.com>.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package publy.gui;

import java.awt.Color;
import java.awt.Component;
import java.awt.Rectangle;
import java.util.ArrayList;
import java.util.List;
import javax.swing.UIManager;
import javax.swing.border.TitledBorder;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import publy.data.category.OutputCategory;
import publy.data.category.conditions.FieldCondition;
import publy.data.category.conditions.FieldContainsCondition;
import publy.data.category.conditions.FieldEqualsCondition;
import publy.data.category.conditions.FieldExistsCondition;
import publy.data.category.conditions.TypeCondition;

/**
 *
 * @author Sander Verdonschot <sander.verdonschot at gmail.com>
 */
public class ConditionsDialog extends javax.swing.JDialog {

    private OutputCategory category;
    private TypeCondition typeCondition;
    private List<FieldCondition> fieldConditions;

    /**
     * Creates new form ConditionsDialog
     */
    public ConditionsDialog(java.awt.Frame parent, OutputCategory category) {
        super(parent, true);

        this.category = category;
        typeCondition = new TypeCondition(category.getTypeCondition());
        
        fieldConditions = new ArrayList<>(category.getFieldConditions().size());
        
        for (FieldCondition c : category.getFieldConditions()) {
            if (c instanceof FieldExistsCondition) {
                fieldConditions.add(new FieldExistsCondition((FieldExistsCondition) c));
            } else if (c instanceof FieldEqualsCondition) {
                fieldConditions.add(new FieldEqualsCondition((FieldEqualsCondition) c));
            } else if (c instanceof FieldContainsCondition) {
                fieldConditions.add(new FieldContainsCondition((FieldContainsCondition) c));
            } else {
                throw new AssertionError("Unexpected field condition type: " + c.getClass());
            }
        }

        initComponents();
        applyStyles();
        populateValues();
        setLocationRelativeTo(parent);
    }

    private void applyStyles() {
        UIStyles.applyHeaderStyle(typeHeader, testHeader);
        UIStyles.applyHeaderStyle((TitledBorder) fieldConditionsScrollPane.getBorder());
    }

    private void populateValues() {
        // Type condition
        if (typeCondition.isInverted()) {
            typeInvertCheckBox.setSelected(true);
            typeInvertCheckBox.setForeground(UIManager.getDefaults().getColor("CheckBox.foreground"));
            typeLabel.setText(typeLabel.getText().substring(0, 1).toLowerCase() + typeLabel.getText().substring(1));
        } else {
            typeInvertCheckBox.setSelected(false);
            typeInvertCheckBox.setForeground(Color.GRAY);
            typeLabel.setText(typeLabel.getText().substring(0, 1).toUpperCase() + typeLabel.getText().substring(1));
        }

        typeTextField.setText(makeString(typeCondition.getTypes()));
        
        // Field conditions
        for (int i = 0; i < fieldConditions.size(); i++) {
            fieldConditionsPanel.add(new FieldConditionPanel(fieldConditions.get(i), fieldConditions, i), i);
        }
        
        fieldConditionsPanel.revalidate();
    }
    
    private String makeString(List<String> values) {
        StringBuilder text = new StringBuilder();
        boolean first = true;

        for (String val : values) {
            if (first) {
                first = false;
            } else {
                text.append(';');
            }

            text.append(val);
        }

        return text.toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typeHeader = new javax.swing.JLabel();
        typeSeparator = new javax.swing.JSeparator();
        typeInvertCheckBox = new javax.swing.JCheckBox();
        typeLabel = new javax.swing.JLabel();
        typeTextField = new javax.swing.JTextField();
        fieldConditionsScrollPane = new javax.swing.JScrollPane();
        fieldConditionsPanel = new javax.swing.JPanel();
        addConditionButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        testHeader = new javax.swing.JLabel();
        testSeparator = new javax.swing.JSeparator();
        testButton = new javax.swing.JButton();
        testScrollPane = new javax.swing.JScrollPane();
        testOutputTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Publy " + UIConstants.MAJOR_VERSION + "." + UIConstants.MINOR_VERSION + " - Conditions");

        typeHeader.setText("Types");

        typeInvertCheckBox.setText("Not");
        typeInvertCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeInvertCheckBoxActionPerformed(evt);
            }
        });

        typeLabel.setText("One of");

        typeTextField.getDocument().addDocumentListener(new DocumentListener() {
            public void insertUpdate(DocumentEvent e) {
                typeTextFieldTextChanged(e);
            }
            public void removeUpdate(DocumentEvent e) {
                typeTextFieldTextChanged(e);
            }
            public void changedUpdate(DocumentEvent e) {
                //Plain text components do not fire these events
            }
        });

        fieldConditionsScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Fields"));

        fieldConditionsPanel.setLayout(new javax.swing.BoxLayout(fieldConditionsPanel, javax.swing.BoxLayout.PAGE_AXIS));

        addConditionButton.setText("Add filter");
        addConditionButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        addConditionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addConditionButtonActionPerformed(evt);
            }
        });
        fieldConditionsPanel.add(addConditionButton);

        fieldConditionsScrollPane.setViewportView(fieldConditionsPanel);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        okButton.setText("Save");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        testHeader.setText("Test");

        testButton.setText("Test");
        testButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testButtonActionPerformed(evt);
            }
        });

        testOutputTextArea.setEditable(false);
        testOutputTextArea.setColumns(20);
        testOutputTextArea.setRows(3);
        testScrollPane.setViewportView(testOutputTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(typeHeader)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(typeSeparator))
                    .addComponent(fieldConditionsScrollPane)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(testHeader)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(testSeparator))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(testScrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(typeInvertCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(typeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(typeTextField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(testButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                                .addComponent(okButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelButton)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(typeSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeHeader))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeInvertCheckBox)
                    .addComponent(typeLabel)
                    .addComponent(typeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(fieldConditionsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(testHeader)
                    .addComponent(testSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(testScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(testButton)
                    .addComponent(cancelButton)
                    .addComponent(okButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void typeTextFieldTextChanged(DocumentEvent e) {
        typeCondition.setTypes(typeTextField.getText().split(";"));
    }

    private void addConditionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addConditionButtonActionPerformed
        FieldCondition cond = new FieldExistsCondition(false, "field");
        fieldConditions.add(cond);
        FieldConditionPanel newComponent = new FieldConditionPanel(cond, fieldConditions, fieldConditions.size() - 1);

        fieldConditionsPanel.add(newComponent, fieldConditionsPanel.getComponentCount() - 1); // Add the new object before the 'Add' button
        fieldConditionsPanel.revalidate(); // Recompute the layout and propagate the changes
        fieldConditionsPanel.scrollRectToVisible(new Rectangle(0, Integer.MAX_VALUE, 0, 0)); // Scroll to the bottom
    }//GEN-LAST:event_addConditionButtonActionPerformed

    private void typeInvertCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeInvertCheckBoxActionPerformed
        if (typeInvertCheckBox.isSelected()) {
            typeCondition.setInverted(true);
            
            typeInvertCheckBox.setForeground(UIManager.getDefaults().getColor("CheckBox.foreground"));
            typeLabel.setText(typeLabel.getText().substring(0, 1).toLowerCase() + typeLabel.getText().substring(1));
        } else {
            typeCondition.setInverted(false);
            
            typeInvertCheckBox.setForeground(Color.GRAY);
            typeLabel.setText(typeLabel.getText().substring(0, 1).toUpperCase() + typeLabel.getText().substring(1));
        }
    }//GEN-LAST:event_typeInvertCheckBoxActionPerformed

    private void testButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_testButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // Sync settings to the category
        category.setTypeCondition(typeCondition);
        category.setFieldConditions(fieldConditions);
        
        dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addConditionButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel fieldConditionsPanel;
    private javax.swing.JScrollPane fieldConditionsScrollPane;
    private javax.swing.JButton okButton;
    private javax.swing.JButton testButton;
    private javax.swing.JLabel testHeader;
    private javax.swing.JTextArea testOutputTextArea;
    private javax.swing.JScrollPane testScrollPane;
    private javax.swing.JSeparator testSeparator;
    private javax.swing.JLabel typeHeader;
    private javax.swing.JCheckBox typeInvertCheckBox;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JSeparator typeSeparator;
    private javax.swing.JTextField typeTextField;
    // End of variables declaration//GEN-END:variables
}
