/*
 * Copyright 2015 Sander Verdonschot <sander.verdonschot at gmail.com>.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package publy.gui;

import java.nio.file.Files;
import java.nio.file.Path;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import publy.data.settings.Settings;
import publy.io.settings.SettingsFinder;
import publy.io.settings.SettingsImporter;

/**
 *
 * @author Sander Verdonschot <sander.verdonschot at gmail.com>
 */
public class WelcomeDialog extends javax.swing.JDialog {

    private Settings settings = Settings.defaultSettings();

    /**
     * Creates new form WelcomeDialog
     *
     * @param parent
     */
    public WelcomeDialog(java.awt.Frame parent) {
        super(parent, true);
        initComponents();

        importDirectoryChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
    }

    /**
     * The settings selected by the user. Either the default settings, or
     * settings imported from an older version of Publy. This method returns
     * the default settings until this dialog has been made visible.
     *
     * @return
     */
    public Settings getSettings() {
        return settings;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        importDirectoryChooser = new javax.swing.JFileChooser();
        welcomeLabel = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        importButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Publy - Hello!");

        welcomeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/publy/gui/resources/logo-100.png"))); // NOI18N
        welcomeLabel.setText("<html>Hey, it looks like this is the first time you're running Publy!<br><b>Please set up your configuration to get started.</b><br>You can also import the configuration of an existing installation of Publy.<br><br>(If you've run Publy before, something might have happened to your configuration file.)</html>");
        welcomeLabel.setIconTextGap(10);

        okButton.setText("Start fresh");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(okButton);

        importButton.setText("Import...");
        importButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(importButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    private void importButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importButtonActionPerformed
        int opened = importDirectoryChooser.showOpenDialog(this);

        if (opened == JFileChooser.APPROVE_OPTION) {
            Path selected = importDirectoryChooser.getSelectedFile().toPath();
            Path settingsFile;

            try {
                // Find Publy
                settingsFile = SettingsFinder.findSettingsFileInFileTree(selected);
            } catch (Exception ex) {
                importError("An error occurred while looking for the settings.", ex);
                return;
            }

            if (settingsFile == null || !Files.exists(settingsFile) || !Files.isRegularFile(settingsFile)) {
                importError("No settings file was found in this folder.");
                return;
            }

            try {
                // Import settings
                settings = SettingsImporter.importSettings(settingsFile);
            } catch (Exception ex) {
                importError("An error occurred while parsing the settings file.", ex);
                return;
            }

            if (settings == null) {
                importError("Import failed.");
                return;
            }

            dispose();
        }
    }//GEN-LAST:event_importButtonActionPerformed

    private void importError(String message) {
        JOptionPane.showMessageDialog(this,
                message,
                "Publy - Import error",
                JOptionPane.ERROR_MESSAGE);
        System.err.println(message);
    }

    private void importError(String message, Exception ex) {
        JOptionPane.showMessageDialog(this,
                message,
                "Publy - Import error",
                JOptionPane.ERROR_MESSAGE);
        System.err.println(message);
        ex.printStackTrace();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton importButton;
    private javax.swing.JFileChooser importDirectoryChooser;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
