/*
 * Copyright 2013 Sander Verdonschot <sander.verdonschot at gmail.com>.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package publy.io.bibtex;

import java.io.BufferedWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import publy.data.bibitem.BibItem;
import publy.data.category.OutputCategory;
import publy.data.settings.FormatSettings;
import publy.gui.UIConstants;
import publy.io.PublicationListWriter;

/**
 *
 * @author Sander Verdonschot <sander.verdonschot at gmail.com>
 */
public class BibtexPublicationListWriter extends PublicationListWriter {

    private int count;

    public BibtexPublicationListWriter(FormatSettings settings) {
        super(settings);
    }

    @Override
    protected void writePublicationList(BufferedWriter out) throws IOException {
        // Initialize the count
        if (getSettings().getNumbering() == FormatSettings.Numbering.GLOBAL) {
            if (getSettings().isReverseNumbering()) {
                count = 0;

                for (OutputCategory c : getCategories()) {
                    count += c.getItems().size();
                }
            } else {
                count = 1;
            }
        }

        // Write the body
        for (OutputCategory c : getCategories()) {
            writeCategory(c, out);
        }
        
        // Credit line and last modified
        out.write("-- Generated by Publy " + UIConstants.MAJOR_VERSION + "." + UIConstants.MINOR_VERSION + ".  Last modified on "  + (new SimpleDateFormat("d MMMM yyyy")).format(new Date()) + ".");
        out.newLine();
    }

    private void writeCategory(OutputCategory c, BufferedWriter out) throws IOException {
        // Reset the count if necessary
        if (getSettings().getNumbering() == FormatSettings.Numbering.LOCAL) {
            if (getSettings().isReverseNumbering()) {
                count = c.getItems().size();
            } else {
                count = 1;
            }
        }

        out.write("-- " + c.getName() + ".");
        out.newLine();
        out.newLine();

        for (BibItem item : c.getItems()) {
            // Write the appropriate number
            if (getSettings().getNumbering() != FormatSettings.Numbering.NONE) {
                out.write("-- " + count + ".");
                out.newLine();

                if (getSettings().isReverseNumbering()) {
                    count--;
                } else {
                    count++;
                }
            }

            writeBibtex(item, out);

            out.newLine();
        }

        out.newLine();

        // Reset the count if necessary
        if (getSettings().getNumbering() == FormatSettings.Numbering.LOCAL) {
            count = 0;
        }
    }

    private void writeBibtex(BibItem item, BufferedWriter out) throws IOException {
        // Item type
        out.write("@" + item.getType() + "{" + item.getId() + ",");
        out.newLine();

        // The first field should omit the connecting ",".
        boolean first = true;

        // Get the proper format for authors
        if (item.anyNonEmpty("author")) {
            out.write("  author={");

            for (int i = 0; i < item.getAuthors().size(); i++) {
                out.write(item.getAuthors().get(i).getName());

                if (i < item.getAuthors().size() - 1) {
                    out.write(" and ");
                }
            }

            out.write("}");

            first = false;
        }

        for (String field : item.getMandatoryFields()) {
            if (!field.equals("author")) {
                if (first) {
                    first = false;
                } else {
                    out.write(",");
                    out.newLine();
                }

                out.write("  ");
                out.write(field);
                out.write("={");
                out.write(item.get(field));
                out.write("}");
            }
        }

        for (String field : item.getOptionalFields()) {
            String v = item.get(field);

            if (!field.equals("author") && v != null && !v.isEmpty()) {
                if (first) {
                    first = false;
                } else {
                    out.write(",");
                    out.newLine();
                }

                out.write("  ");
                out.write(field);
                out.write("={");
                out.write(item.get(field));
                out.write("}");
            }
        }

        out.newLine();
        out.write("}");
        out.newLine();
    }
}
